# Generated by Django 5.0.3 on 2024-03-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
    ]
