# Generated by Django 5.0.3 on 2024-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя обратившегося')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта обратившегося')),
                ('content', models.TextField(blank=True, verbose_name='Текст обращения')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='articles_co_created_67707e_idx')],
            },
        ),
    ]
