# Generated by Django 5.0.3 on 2024-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_comment_options_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
